language: python
dist: trusty
sudo: false

cache:
  directories:
    - $HOME/.pip-cache/

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE budgettest;'

env:
  global:
    - MYSQL_CONNSTRING='mysql+pymysql://root@127.0.0.1:3306/budgettest?charset=utf8mb4'
    - SETTINGS_MODULE=biweeklybudget.settings_example

matrix:
  include:
    - python: "2.7"
      env: TOXENV=py27 PIP_DOWNLOAD_CACHE=$HOME/.pip-cache
    - python: "3.3"
      env: TOXENV=py33 PIP_DOWNLOAD_CACHE=$HOME/.pip-cache
    - python: "3.4"
      env: TOXENV=py34 PIP_DOWNLOAD_CACHE=$HOME/.pip-cache
    - python: "3.5"
      env: TOXENV=py35 PIP_DOWNLOAD_CACHE=$HOME/.pip-cache
    - python: "3.6"
      env: TOXENV=py36 PIP_DOWNLOAD_CACHE=$HOME/.pip-cache
    - python: "2.7"
      env: TOXENV=acceptance27 PIP_DOWNLOAD_CACHE=$HOME/.pip-cache
    - python: "3.6"
      env: TOXENV=acceptance36 PIP_DOWNLOAD_CACHE=$HOME/.pip-cache
    - python: "3.6"
      env: TOXENV=docs PIP_DOWNLOAD_CACHE=$HOME/.pip-cache

install:
- virtualenv --version
- git config --global user.email "travisci@jasonantman.com"
- git config --global user.name "travisci"
- pip install tox
- pip install codecov
- pip freeze
- virtualenv --version
script:
  - tox -r

after_success:
  - codecov

notifications:
  email:
    on_success: always
    on_failure: always
  pushover:
    users:
    - secure: "YNXj3CkaFff3iRPRFIilCRIacCA388Kj2AWXz6YCg8uQ7cqygNG/Lp3Vdcebth4i189unLfR95LHM2iLvN+jfXd5aHuqxtpFTtVGSy2/Y91AudkVdzI5iMZbZh/x676OoaHSShl3qREkcLMWQZYXUQitBHaIquDQsvFvHVxQHYMzLTMQ8B/DQHa2dfSBkfIO9umQwf+I/tXj+XkZCDQ6PMS9pZPTCe7jnHpfiks7KE4ukaaRpB+tNYFb9Zyht0x/DrmSrh1A9oy8MNZrsHejnWaIZ9gNEQ22WbbmSOPz4xihS4s5zf5KczVPMFaUlkFqu7uCZHJ5znmkd9wKYm/+X9pqhiGg4JuckAqEitps+9asy829nBZgWwxK2YRNG9XuAsreTZjbBsrjrOAD/I1t+/rhCU10NX9pFaNH4tYYkRQXkI5ASHcrUD0zkmlbg6sXiOSb9A6UvMverCWiK7iCcSPL31k9fMDqaxxc7kxDJlRCniuoqvXSh7ICva9ArtHa3Ouag2B2kMZ17OABRDRDvRwaAcYoCdSULyDFCsujUivTfecq5VtBau/XZAwnYqi7NmO76TizcWSbDhDxrzQNOoUMjFn7Y8U9xm3ua/fMbY3XEA6APXbbxp9+51UKujmihVhkzZwv8nljAXNYiBC6RkcWOiiHpCW9n4ANusNDSYs="
    api_key:
      secure: "on1S1hje1M8+NvqZhSROGDuTuyreIB6+CftAgOEpd8NZW+7DX66+1HdtQ7zfOe1TbYK3tYv/CFipm7UIaW84nKBXhUNy/YOvzHjAT7TgpqR3YpN7u/4fCqLWFiGp2Uyi8u+WQtcv4VKFfSyXD6J7Fk+5JyzczrV++Vlp2kgnkQ2ZfXU0lU3AyGCdnGvt9rLn4comuLuVOEyKllS12i9MUzLgF4cItOVHtwPysHmdYd+nylT0wUatbUL2f4Kb94vrjtgRqBEdCq8XUhMDjbzQ9JEdn/FgnigWswFBOOjm//2DZSTjltl0L6MzLkSSEXaTOFn63X+n0hWzA01WrIZf6mTjUTtqHUo8a2vHhBjOZRA5U+R83GXaOBNqbBGNoLGSBmUZJiz0l7gTGoy4MF+jzh8LmItau81cBDuY/l+QW3AkpsriGjO1dw0cyiEIaWI7FHYt7mesCkLQ1A7mQgsH+TiDZSDYYy5QfDY7e9PPbY5ABaGOr+Izdryy3Zdh4adjhFqBSG4wXi9m/a+P/DzPNXTXX7meZoSwPy7El/yPUsVpTjbB2iOGKvgM7MM8z/QeD/0sTDQ4ZbXDUk3Swwq9jRj712BBWj7UiEcoPoClEMxEvRQuzlcFPS8BstHwElMWne6m40yjD845fXs0DS0zxGps2o1USCdArew4LrCiFm0="
branches:
  except:
    - "/^noci-.*$/"
